language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

jobs:
  include:
    - stage: "Test Provider"
      name: "Unit"
      script: |
        echo ">>> Run unit/integration tests of Provider app"
        ./gradlew test --info
      if: env(PACT_URL) IS NOT present

    - name: "Verify contract"
      script: |
        echo ">>> Verify the provider and publish results back to Pact Broker"
        make verify_and_publish_ci
      if: env(PACT_URL) IS NOT present

    - stage: "Deploy"
      name: "Deploy to prod"
      env:
        - PACT_BROKER_BASE_URL=https://telegacom.pact.dius.com.au
      script: |
        printenv
        make deploy_to_prod
      if: env(PACT_URL) IS NOT present AND branch =~ /^(master).*/

    - stage: "Webhook"
      name: "Verify contract triggered by webhook"
      script: |
        echo ">>> Verify the provider and publish results back to Pact Broker"
        make verify_and_publish_ci
      if: env(PACT_URL) IS present
