language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

jobs:
  include:
    - stage: "Test"
      script: |
        echo ">>> Run unit/integration tests of Provider app"
        ./gradlew test --info


    - stage: "Verify contract"
      script: |
        echo ">>> Verify the provider and publish results back to Pact Broker"
        ./gradlew pactVerify -Ppact.verifier.publishResults=true
